project:
  type: website
  output-dir: docs

website:
  title: "Matrix Metrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: kevin.qmd
        text: Kevin

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

